### ISSUE TITLE
Unable to resolve reveal.js submodule

### ISSUE THREAD

**Issue by mblack88** [githubtraining/caption-this-template#4]
We are behind a corporate firewall and all **https** traffic must traverse through it.
Since **git** doesn't honor the **system** or **http_proxy** or **https_proxy** typical settings we are unable to resolve **https://github.com/hakimel/reveal.js.git**.

This prevents the GH_PAGES functionality to fail to perform for us. 😦 

@beardofedu @brianamarie @crichID

**Comment by brianamarie** [comment]
Ah, understandable how that would cause a problem, @mblack88. 

Have you tried cloning the latest release of the reveal.js repository, and pushing it up to a repository within your firewalls, and pointing to that repository as a submodule?

**Comment by mblack88** [comment]
Yes I have.

Sent from my iPhone

On Oct 29, 2018, at 5:13 AM, Briana Swift <notifications@github.com<mailto:notifications@github.com>> wrote:


Ah, understandable how that would cause a problem, @mblack88<https://github.com/mblack88>.

Have you tried cloning the latest release of the reveal.js repository, and pushing it up to a repository within your firewalls, and pointing to that repository as a submodule?

**Comment by brianamarie** [comment]
@mblack88 👍 I'm happy to help troubleshoot and get that working if you'd like.

**Comment by mblack88** [comment]
Any and all help would be great.

Sent from my iPhone

On Oct 29, 2018, at 7:37 AM, Briana Swift <notifications@github.com<mailto:notifications@github.com>> wrote:


@mblack88<https://github.com/mblack88> 👍 I'm happy to help troubleshoot and get that working if you'd like.

**Comment by brianamarie** [comment]
@mblack88 Since I can't see behind your firewall, I don't know the current setup with the attempt of adding a different submodule. You've gotten the reveal.js set up internally, and then I'm guessing you added it as a submodule within the `caption-this`. Could you post the following information so I can help? 

- From inside the `caption-this` within your firewall, when cloned locally, the output of `ls -al`, and the output of `cat .gitmodules`

If possible, do you have the history for your terminal from when you added the new submodule? Submodules can be tricky and unintuitive, so there's a chance that even if it's added to your `.gitmodules`, it isn't 'initialized' yet. If this is the case, which I'm just guessing is one possibility right now, then you would want to run `git submodule update --init --recursive`, then commit and push any changes. If you run `git submodule update --init --recursive` and nothing happens, then this isn't what's happening. 

Let's start there @mblack88. Let me know if you have any questions.

**Comment by mblack88** [comment]
Here is my .gitmodule from my repository in GitHub.Ford.com:
[submodule "reveal.js"]
	path = reveal.js
	url = git@github.ford.com:MBLACK88/revel.js.git

locally the submodule has correct content and the link in the repo goes to the correct space.

I have also tried changing github.ford.com to it's proper internal IP address too with no luck.

Note:  I am not turning it back on as we had URL 500 errors this weekend within 12 hours of enabling gh-pages on these repositories.

**Comment by brianamarie** [comment]
@mblack88 I tried a simpler route, to [un-submodule the submodule](https://stackoverflow.com/questions/1759587/un-submodule-a-git-submodule), and pushed it up to a [separate repository](https://github.com/brianamarie/caption-this-no-submodule). On GitHub.com, I'm able to get the [GitHub Pages site](https://brianamarie.github.io/caption-this-no-submodule/#/) to work. 

If you delete the existing `caption-this` template that you have on Enterprise, and replace it with the code from [this example with no submodules](https://github.com/brianamarie/caption-this-no-submodule), are you able to run the script and have participants successfully enable GitHub Pages and see the slides? 

cc @githubtraining/trainers If this works, we may want to move [this repository with no submodule](https://github.com/brianamarie/caption-this-no-submodule) to a repository in `/githubtraining` so we can use it for other customers working within their Enterprise instance. This would have been helpful on site last week (cc @ppremk).

**Comment by mblack88** [comment]
@brianamarie Ok I made reveal.js a standard directory rather than a submodule and I no longer get an error when GHE attempts to render the pages. 
**Butt** I only get a very **boring** page:
![boringpage](https://user-images.githubusercontent.com/21953360/47719075-68cb0580-dc20-11e8-844e-80cfae040cba.png)

The **Right Arrow** also doesn't work.  This is similar to the problem I see when I try to run the pages locally on one of my Linux VMs.

**Comment by brianamarie** [comment]
@mblack88 HmmMmmm OK, good to know. I'm sure you already checked, but the directory does in fact have all of the files, right? It's not an empty one? 🤔

**Comment by mblack88** [comment]
Yep, has all the files as far as I can tell.
I can try and clone the original from GitHub later this morning and then copy it into the subdirectory just to make sure though.

**Comment by brianamarie** [comment]
@mblack88 Thank you for your patience in working through this. I think you should try to clone https://github.com/brianamarie/caption-this-no-submodule from GitHub and push it up to a fresh repository, and we can go from there if it's still not working.

**Comment by mblack88** [comment]
I cloned your repo and then push it up to our enterprise instance just as it was cloned and had the same results as I had before.
Just the same old **boring** page.

**Comment by mblack88** [comment]
I have also tried to “Fork” your repo to my GitHub.com account and I get the same problem.  Very Strange.

https://mblack88.github.io/caption-this-no-submodule/

**Comment by mblack88** [comment]
Timeout maybe found issue.  Please Hold.

**Comment by hectorsector** [comment]
@mblack88 closing this out since it appears it may have been resolved. Please feel free to reopen if it's not.
